Update
status-20X/stylusdb-sql-base pull request #4
Opened 2024-03-26 03:11 UTC by heyhimansh

2024-03-26 03:11 UTC, heyhimansh commented
task 1

2024-03-28 14:26 UTC, techsavvyash commented
what is the intent of this PR?

2024-03-28 14:29 UTC, techsavvyash requested changes

2024-03-28 14:29 UTC, techsavvyash commented on schema.prisma
why do we have a `schema.prisma` here?

2024-03-28 14:29 UTC, techsavvyash commented on query.js
what's the point of this file?

2024-03-28 14:29 UTC, techsavvyash commented on .github/workflows/classroom.yml
> +        setup-command: npm install
why do we need to install the dependencies before each test? 🤔

2024-03-28 14:29 UTC, techsavvyash commented on .github/workflows/classroom.yml
what do you think id the problem in the current github workflows?

2024-03-28 14:29 UTC, techsavvyash commented on .github/.keep
why do we need this if we already have a `workflows/classroom.yml` in the `.github/` folder?

2024-03-28 20:20 UTC, nithieshnaik commented on .github/workflows/classroom.yml
i did not get you

2024-03-28 20:30 UTC, nithieshnaik commented on .github/workflows/classroom.yml
i did not get you

2024-03-28 21:04 UTC, nithieshnaik commented on .github/workflows/classroom.yml
i recently applied for github class so i did not get the id

2024-03-29 05:01 UTC, sidpg123 commented on .github/.keep
in git, empty directories are not tracked, as git looks for changes in folders not in files. But if we want to add an empty directory in our repository we can create .keep file.

2024-04-01 05:48 UTC, techsavvyash commented on .github/.keep
the `.github` folder already has a workflows folder we don't need the `.gitkeep` file its just to keep empty folders.

2024-04-01 05:49 UTC, techsavvyash commented
@heyhimansh you don't have to raise a PR for each step, just keep committing and pushing to the main branch of your fork and your scores will be calculated. Closing this PR.

2024-04-01 05:49 UTC, closed without merging